name: Build project

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production # production secret env variables

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.3' # The Go version to download (if necessary) and use.
      - name: print env
        run: 
          echo "The path to image is ${{ env.IMAGE_PATH }}" 
          echo "The path to image is $IMAGE_PATH" 
      - name: build
        run: go build src/main.go